### PR TITLE
Add QuickSelect algorithm

### PR DESCRIPTION
**Pull request by abonander**
There's not any other crate that I can find that implements this, at least in a useful way. I figured I'd add it here instead of publishing my own just for a couple functions.

Addendum: add versions of the new functions which take ordering functions.

### CODE REVIEW

**Comment by aleksandrpak** [comment]
Thank you for the pull request! 

I am not sure about making median_of\* and in_order\* public. Do you use them outside?

**Comment by abonander** [comment]
I didn't see much harm in making them public since they could be useful to someone. They might be better off moved up to the `select` module, though. Maybe also a `median` convenience function (and variants for inplace and providing an ordering function):

``` rust
pub fn median<T: Ord>(data: &[T]) -> &T {
    qselect(data, data.len() / 2)
}
```

**Comment by aleksandrpak** [comment]
Can you please move them to select module then? If you want you can add the median function but I am ok to merge without it and implement it myself later.

**Comment by abonander** [comment]
@aleksandrpak new commits pushed.

**Pull request merged**
